### ISSUE TITLE
Connect-OciServer fails with "Missing Content - Type header" starting with OCI 7.3.14 

### ISSUE THREAD

**Issue by ohoetger** [ffeldhaus/OnCommand-Insight#7]
```
2022-08-02-08:48:08.716 INFO    Connecting to OCI Server ociserver
WARNING: Login to https://ociserver/rest/v1/login failed via HTTPS protocol. Exception message: The remote server returned an error: (400) Bad Request.
 {
    "errorCode":  "INVALID_REQUEST",
    "errorMessage":  "Missing Content-Type header"
}
Connect-OciServer : Authorization for http://ociserver/rest/v1/login with user admin-user failed
At D:\Scripts\Set_Annotations.ps1:60 char:13
+     $null = Connect-OciServer -Name $OciServerName -Insecure -Credent ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Connect-OciServer
```

**Comment by ffeldhaus** [comment]
It could be that the behaviour on the OCI Server side changed or that there was a change in behaviour by the `Invoke-RestMethod` powershell Cmdlet. It seems that the fix would be to add `-ContentType 'application/json'` at the end of the `Invoke-RestMethod` calls inside `function global:Connect-OciServer` e.g. similar to this:
```
$Response = Invoke-RestMethod -Session Session -Method Post -Uri "$BaseURI/rest/v1/login" -TimeoutSec $Timeout -Headers $Headers -ContentType 'application/json'
```

Can you try that and let me know if it works?

**Comment by hotzg** [comment]
Adding the -ContentType 'application/json' to the method fixed the issue. I tried to make the change in a fork and create a pull request, but for some reason doesn't work for me. Florian, would you mind to add the change to the main code?

**Comment by ffeldhaus** [comment]
I added the fix to the master branch, but I can't easily create a new PowerShell Module. If absolutely necessary, I will create an unsigned Module, but can't upload it to the PowerShell Gallery anymore for easy install.
